### ISSUE TITLE
In Game Configuration not working in 1.11.2

### ISSUE THREAD

**Issue by NovaViper** [CreativeMD/AmbientSounds#11]
I notice that the mod features an in-game config but it doesn't appear to be working on 1.11.2. It spits out this error:

```
[06:34:46] [Client thread/ERROR] [FML]: There was a critical issue trying to build the config GUI for ambientsounds
java.lang.NoSuchMethodException: com.creativemd.ambientsounds.AmbientConfigGUI.<init>(net.minecraft.client.gui.GuiScreen)
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.client.GuiModList.func_146284_a(GuiModList.java:285) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:452) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_73864_a(GuiModList.java:199) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:542) [bho.class:?]
	at net.minecraftforge.fml.client.GuiModList.func_146274_d(GuiModList.java:329) [GuiModList.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:510) [bho.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695) [bes.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

I'm using AmbientSounds 2.0.0 (though the downloaded name says 2.0.4)

**Comment by CreativeMD** [comment]
Maybe you are using an old version of Forge? I tested it with the newest one and everything works fine. I'm sorry that i have not answered yet, i have been quite busy.

**Comment by CreativeMD** [comment]
If you are using 1.12 try out the newest version.

**Comment by CreativeMD** [comment]
I guess it is fixed now, if not just reopen this issue.

**Comment by NovaViper** [comment]
Oh sorry! It is fixed! ^^
