### ISSUE TITLE
Unexpected Error: java.lang.NoSuchMethodError ...

### ISSUE THREAD

**Issue by NaiNonTH** [CreativeMD/AmbientSounds#148]
## **Description**
After I installed the AmbientSounds mod, the game crashed while loading.

## **Error Log**
```
Time: 2022-09-08 20:29:48
Description: Unexpected error

java.lang.NoSuchMethodError: 'java.lang.Object team.creative.creativecore.common.util.registry.NamedHandlerRegistry.getOrThrow(java.lang.String)'
	at team.creative.ambientsounds.block.AmbientBlockFilters.parse(AmbientBlockFilters.java:47)
	at team.creative.ambientsounds.block.AmbientBlockFilters.get(AmbientBlockFilters.java:26)
	at team.creative.ambientsounds.env.feature.AmbientBlockGroup.onClientLoad(AmbientBlockGroup.java:19)
	at team.creative.ambientsounds.AmbientEngine.lambda$onClientLoad$0(AmbientEngine.java:355)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at team.creative.ambientsounds.AmbientEngine.onClientLoad(AmbientEngine.java:355)
	at team.creative.ambientsounds.AmbientEngine.init(AmbientEngine.java:351)
	at team.creative.ambientsounds.AmbientEngine.attemptToLoadEngine(AmbientEngine.java:162)
	at team.creative.ambientsounds.AmbientEngine.loadAmbientEngine(AmbientEngine.java:187)
	at team.creative.ambientsounds.AmbientTickHandler.onTick(AmbientTickHandler.java:243)
	at team.creative.creativecore.CreativeFabricLoader.lambda$registerClientTick$1(CreativeFabricLoader.java:47)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$bpe000$onEndTick(class_310.java:8473)
	at net.minecraft.class_310.method_1574(class_310.java:1907)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

## **Attachments**
**Log:**
[latest.log](https://github.com/CreativeMD/AmbientSounds/files/9527205/latest.log)

**Crash Report:**
[crash-2022-09-08_20.29.48-client.txt](https://github.com/CreativeMD/AmbientSounds/files/9527214/crash-2022-09-08_20.29.48-client.txt)

## **Versions and Surroundings**
**Mod Version:** v5.2.3
**Minecraft Version:** v1.19.2
**Mod Loader Version:** Fabric Mod Loder 0.14.9

**Comment by NaiNonTH** [comment]
Issue fixed after updating CreativeCore.
