### ISSUE TITLE
Incompatible mod set! Whats wrong?

### ISSUE THREAD

**Issue by MisterRickiy** [CreativeMD/AmbientSounds#182]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, any version.
Unmet dependency listing:
	 - Mod 'AmbientSounds' (ambientsounds) 5.2.20 requires any version of fabric, which is missing!
	 - Mod 'CreativeCore' (creativecore) 2.10.24 requires any version of fabric, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MisterRickiy** [comment]
Fabric API is missing!

**Comment by vinnyg0621** [comment]
wait... it requires fabric API?! no!!!!!!!!!!!!!
