### ISSUE TITLE
log spamming errors (5.3.9 for 1.20.1 on quilt)

### ISSUE THREAD

**Issue by deli73** [CreativeMD/AmbientSounds#217]
the log is repeatedly spamming these errors:
```
[21:53:53] [Sound engine/WARN]: Mixin transformation of team.creative.creativecore.mixin.GroupResourcePackAccessor failed
org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin team.creative.creativecore.mixin.GroupResourcePackAccessor. The mixin is missing from #creativecore:creativecore.mixins.json which owns package team.creative.creativecore.mixin.* and the mixin has not been applied.
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:334) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:454) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:241) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:161) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:147) ~[quilt-loader-0.24.0.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:239) ~[quilt-loader-0.24.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at team.creative.creativecore.common.util.mc.PlatformResourceUtils.length(PlatformResourceUtils.java:15) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.creativecore.common.util.mc.ResourceUtils.length(ResourceUtils.java:32) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.creativecore.common.util.mc.ResourceUtils.length(ResourceUtils.java:21) ~[creativecore-2.11.24.i0:0/:?]
	at team.creative.ambientsounds.AmbientSound$SoundStream$1.create(AmbientSound.java:459) ~[ambientsounds-5.3.9.i0:0/:?]
	at net.minecraft.class_4856.method_19720(class_4856.java:45) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4224.method_19640(class_4224.java:151) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4224.method_19658(class_4224.java:166) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4235.method_19731(class_4235.java:82) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[minecraft-1.20.1.i0:0/:?]
	at net.minecraft.class_4238.method_19765(class_4238.java:42) ~[minecraft-1.20.1.i0:0/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

this is our mod list, in case any are relevant:
```
  [✔] AmbientSounds_FABRIC_v5.3.9_mc1.20.1
  [✔] another_furniture-fabric-1.20.1-3.0.1
  [✔] audioplayer-fabric-1.20.1-1.9.0
  [✔] AxesAreWeapons-1.7.3-fabric-1.20.2
  [✔] bclib-3.0.14
  [✔] better-end-4.0.11
  [✔] BetterF3-7.0.2-Fabric-1.20.1
  [✔] betterladdersmod-1.20.x-No-3D-Model
  [✔] better-nether-9.0.10
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] carpeted-1.20-1.4-fabric
  [✔] cloth-config-11.1.118-fabric
  [✔] comforts-quilt-6.3.6+1.20.1
  [✔] connected-doors-1.2+1.20
  [✔] Continents_1.20.4_v1.1.4
  [✔] CreativeCore_FABRIC_v2.11.24_mc1.20.1
  [✔] cristellib-1.1.5-fabric
  [✔] ctov-3.4.2
  [✔] DripSounds-1.19.4-0.3.2
  [✔] DynamicSurroundings-Fabric-1.20.1-0.3.3
  [✔] ears-fabric-1.20-1.4.6
  [✔] effective-2.2.0+1.20.1
  [✔] elytratrims-fabric-2.0.3+1.20.1
  [✔] emi_loot-0.6.5+1.20.1
  [✔] emi_ores-0.3+1.20.1
  [✔] emi-1.1.3+1.20.1+fabric
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] exposure-1.20.1-1.4.1-fabric
  [✔] fabrication-3.4.11+1.20
  [✔] fabrictailor-2.1.2
  [✔] fallingleaves-1.15.4+1.20.1
  [✔] ferritecore-6.0.1-fabric
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] geckolib-fabric-1.20.1-4.4.4
  [✔] grapplemod-1.20(.1)-v1.7
  [✔] hearth_and_home-fabric-1.20.1-2.0.1
  [✔] indium-1.0.30+mc1.20.4
  [✔] iris-mc1.20.1-1.6.17
  [✔] Kaffee's_Dual_Ride-mc1.20.1-1.1.0
  [✔] KeepSomeInventory-v1.3.3
  [✔] linearxp-1.0.1
  [✔] lithostitched-fabric-1.20.1-1.1.5
  [✔] matchbox-0.3.1-1.20.1
  [✔] memoryleakfix-fabric-1.17+-1.1.5
  [✔] Metabolism-Fabric-1.20.1-2.1.3
  [✔] modelfix-1.14-fabric
  [✔] modmenu-7.2.2
  [✔] moonlight-1.20-2.7.2-fabric
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] naturalist-fabric-4.0.3-1.20.1
  [✔] PuzzlesLib-v8.1.17-1.20.1-Fabric
  [✔] qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1
  [✔] remove-terralith-intro-message-1.0
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] sound-physics-remastered-fabric-1.20.1-1.3.1
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Terralith_1.20.4_v2.4.11
  [✔] tinkerers-smithing-2.6.7+1.20
  [✔] tool-trims-mod-v2-0-2e-1-20
  [✔] Towns-and-Towers-1.12-Fabric+Forge
  [✔] voicechat-fabric-1.20.1-2.5.9
  [✔] wakes-0.2.3
  [✔] walljump-1.20.1-1.1.5-fabric
  [✔] XaerosWorldMap_1.38.1_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.2.2+1.20
  [✔] YungsApi-1.20-Fabric-4.0.4
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.4
 ```

**Comment by deli73** [comment]
nvm this is a duplicate of [Issue 205 on CreativeCore](https://github.com/CreativeMD/CreativeCore/issues/205). we turned off sound offset and that seems to fix things.
