### ISSUE TITLE
Wind.json BEGIN_ARRAY in place of BEGIN_OBJECT

### ISSUE THREAD

**Issue by Oxeus** [CreativeMD/AmbientSounds#221]
No crashing errors but it looks like wind sound effects is causing an error in my version of the game/mod. 

I am running v6.0.0_mc1.20.6 with Sodium, Iris, and Indium as the renderer.

Running the game with and without Indium gets the same error.

Log:

[20:04:52] [Render thread/ERROR]: Failed to load AmbientSoundCollection in ambientsounds:basic/sound_collections/wind.json ambientsounds
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
	at team.creative.ambientsounds.engine.AmbientEngine.loadMultiple(AmbientEngine.java:171) ~[AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar:?]
	at team.creative.ambientsounds.engine.AmbientEngine.attemptToLoadEngine(AmbientEngine.java:120) ~[AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar:?]
	at team.creative.ambientsounds.engine.AmbientEngine.loadAmbientEngine(AmbientEngine.java:206) ~[AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar:?]
	at team.creative.ambientsounds.AmbientSounds.reload(AmbientSounds.java:45) ~[AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar:?]
	at team.creative.ambientsounds.AmbientSounds$1.method_18788(AmbientSounds.java:65) ~[AmbientSounds_FABRIC_v6.0.0_mc1.20.6.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $
	at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:165) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:89) ~[gson-2.10.1.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]

**Comment by CreativeMD** [comment]
Thanks for reporting this issue. Small oversight. Fixed it in the newest version.
