### ISSUE TITLE
Tried to access private method

### ISSUE THREAD

**Issue by TheCommandoChicken** [CreativeMD/AmbientSounds#238]
On fabric API 0.100.3, Minecraft 1.21. Latest version of the mod is installed.
```Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalAccessError: class team.creative.ambientsounds.engine.AmbientEngine tried to access private method 'void net.minecraft.class_2960.<init>(java.lang.String, java.lang.String)' (team.creative.ambientsounds.engine.AmbientEngine and net.minecraft.class_2960 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @52af6cff)
	at team.creative.ambientsounds.engine.AmbientEngine.<clinit>(AmbientEngine.java:47) ~[AmbientSounds_FABRIC_v6.0.2_mc1.20.6.jar:?]
	at team.creative.ambientsounds.engine.AmbientTickHandler.onTick(AmbientTickHandler.java:150) ~[AmbientSounds_FABRIC_v6.0.2_mc1.20.6.jar:?]
	at team.creative.creativecore.CreativeFabricLoader.lambda$registerClientTick$1(CreativeFabricLoader.java:40) ~[CreativeCore_FABRIC_v2.11.34_mc1.21.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.3.1+8f3583aed1-e56ba4d7ddcf6ff8.jar:?]
	at net.minecraft.class_310.handler$bcn001$fabric-lifecycle-events-v1$onEndTick(class_310.java:8183) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2012) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1246) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]```

**Comment by TheCommandoChicken** [comment]
Update: this appears to be due to 6.0.2 supporting both 1.20.6 and 1.21, causing Prism Launcher to fail to recognize it as an update when migrating from 1.20.6 to 1.21.

**Comment by CreativeMD** [comment]
Alright. Then updating the mod to 1.21 shouldn't be a big deal I guess.
