### ISSUE TITLE
[1.14.4] Client Side Class Loading Server Side

### ISSUE THREAD

**Issue by Morpheus1101** [CreativeMD/AmbientSounds#54]
Forge *.99
AS: 3.0.14

`---- Minecraft Crash Report ----
// You're mean.

Time: 10/12/19 1:06 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Ambient Sounds (ambientsounds) encountered an error during the common_setup event phase
ยง7Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:154) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:46) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}`

**Comment by CreativeMD** [comment]
You should not use AmbientSounds on server side.
